collection_name : cloth_ai
persist_directory : chroma_db
k :  3
data_path : data
md5_hex_store : md5.txt
allow_knowledge_file_type : ["txt","pdf"]

chunk_size : 220
chunk_overlap : 30
separators : ["\n\n","。",".","?","？","!"," ",","]
