from typing import Protocol

from stylemate.domain.models import ConversationState, PendingAction, UserDocument


class AgentRepository(Protocol):
    def load_conversation(
        self, owner_id: str, conversation_id: str
    ) -> ConversationState: ...

    def save_conversation(self, state: ConversationState) -> None: ...

    def list_conversations(self, owner_id: str) -> list[dict]: ...

    def clear_conversation(self, owner_id: str, conversation_id: str) -> None: ...

    def save_pending(self, action: PendingAction) -> None: ...

    def get_pending(self, owner_id: str, conversation_id: str) -> PendingAction | None: ...

    def clear_pending(self, owner_id: str, conversation_id: str) -> None: ...

    def save_document(self, document: UserDocument) -> None: ...

    def list_documents(self, owner_id: str, conversation_id: str) -> list[UserDocument]: ...

    def delete_document(
        self, owner_id: str, conversation_id: str, document_id: str
    ) -> None: ...

    def clear_documents(self, owner_id: str, conversation_id: str) -> None: ...

