from typing import Protocol

from stylemate.domain.models import FavoriteOutfit, Garment, OutfitFeedback


class WardrobeRepository(Protocol):
    def list_garments(self, owner_id: str) -> list[Garment]: ...

    def get_garment(self, owner_id: str, garment_id: str) -> Garment | None: ...

    def save_garment(self, owner_id: str, garment: Garment) -> None: ...

    def delete_garment(self, owner_id: str, garment_id: str) -> None: ...

    def find_garment_by_hash(self, owner_id: str, image_hash: str) -> Garment | None: ...

    def get_profile(self, owner_id: str) -> dict[str, str]: ...

    def save_profile(self, owner_id: str, profile: dict[str, str]) -> None: ...

    def save_favorite(self, favorite: FavoriteOutfit) -> None: ...

    def list_favorites(self, owner_id: str) -> list[FavoriteOutfit]: ...

    def save_feedback(self, feedback: OutfitFeedback) -> None: ...

